### ISSUE TITLE
Libvirt::Exception::LibvirtError: cannot send data: Broken pip

### ISSUE THREAD

**Issue by hwatkins** [mitchellh/libvirt-rb#10]
I'm using libvirt-rb inside an eventmachine reactor loop, here's some sample code

class VmCheck
# Adds a periodic timer to the Eventmachine reactor loop
  def initialize
    EM.add_periodic_timer(3) do
      vm_status
    end
  end

   def vm_status
    begin
     cnx = Libvirt::Connection.new
     <Check status of VMs>
    rescue Exception => ex
    ...
    end
end
It runs for a couple of iterations and then I get:
#<Libvirt::Exception::LibvirtError: cannot send data: Broken pipe>

I could handle the exception and try to reconnect, but I didn't see obvious hooks to do that.

Thanks

**Comment by mitchellh** [comment]
Hm, is this consistent for you? I mean, everytime you run the program you get this exception? I'm unable to reproduce it myself. 

But you can definitely try to reconnect by simply throwing away that conneciton object and reinitializing it `cxn = Libvirt.connect`.

Also, `Libvirt.connect` is shorthand for `Libvirt::Connection.new` :)

**Comment by hwatkins** [comment]
I was allocating a nested `Libvirt::Connection`, once you hit this condition allocating a `Libvirt.connect` or `Libvirt::Connection.new` will always fail.

Here is a test that will fail after 10 iterations: [pipetest.rb](https://gist.github.com/733679)

I changed my code around to share the same connection an it works overnight now.

Thanks

**Comment by mitchellh** [comment]
Abandoned gem, please fork or find another maintainer. Sorry!
