### ISSUE TITLE
Poor nokogiri dependency prevents usage with fog

### ISSUE THREAD

**Issue by mpalmer** [mitchellh/libvirt-rb#18]
Fog needs nokogiri ~> 1.5, libvirt needs ~> 1.4.3.  Since ~> strips the last element and then increments, it means that libvirt needs nokogiri >= 1.4.3, < 1.5.0.  This is bad, and also almost certainly invalid.  Please update the dependency spec to be ~> 1.4, >= 1.4.3.  If you're not interested in continuing maintenance of this package, please let me know, I'd be happy to take it on and make a new release of the gem.

**Comment by mitchellh** [comment]
Abandoned gem, please fork or find another maintainer. Sorry!
