### ISSUE TITLE
Create domain fails in Xen when domain (domU) name contains whitespaces

### ISSUE THREAD

**Issue by rubiojr** [mitchellh/libvirt-rb#7]
Sample code:

```
spec = Libvirt::Spec::Domain.new
spec.hypervisor = :xen
# >>>  this works
spec.name = "test"
# >>> this wont work
spec.name = "test foo"
spec.os.type = :linux
spec.memory = 123456 # KB
```

---

/var/log/xen/xend-debug.log output:

http://gist.github.com/640121

**Comment by mitchellh** [comment]
It looks like the problem is that Xen doesn't like the name of the VM. In that case, the error that xen is raising is valid. Does libvirt raise an error as well? 

I have no interest in doing validation for the various hypervisors, since I delegate that responsibility to the hypervisors themselves.

**Comment by calavera** [comment]
agree, libvirt should be who decide what to do with that errors.

**Comment by rubiojr** [comment]
Right.

I believe Xen expects a valid hostname in the name attribute. Libvirt just proxies the error.
